- name: Hello World Sample
  hosts: all
  tasks:

    - name: Check if port 9092 is listening
      wait_for:
        port: 9092
        delay: 5
        timeout: 10000000
        msg: "Timeout waiting for 80 to respond"
      register: port_check
