- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Check if port 80 is listening
      wait_for:
        port: 80
        delay: 5
        timeout: 10
        msg: "Timeout waiting for 80 to respond"
      register: port_check
